### ISSUE TITLE
[Error] Build scheduled during frame

### ISSUE THREAD

**Issue by PAException** [Pyozer/introduction_screen#140]
Stacktrace thrown while rotating phone. 

Stack
```
Build scheduled during frame.

...

The relevant error-causing widget was: 
  IntroductionScreen IntroductionScreen:file:///C:/Users/huerk/Desktop/engelsburg-planer/lib/src/introduction.dart:36:18
When the exception was thrown, this was the stack: 
#0      WidgetsBinding._handleBuildScheduled.<anonymous closure> (package:flutter/src/widgets/binding.dart:747:9)
#1      WidgetsBinding._handleBuildScheduled (package:flutter/src/widgets/binding.dart:770:6)
#2      BuildOwner.scheduleBuildFor (package:flutter/src/widgets/framework.dart:2488:24)
#3      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4569:12)
#4      State.setState (package:flutter/src/widgets/framework.dart:1134:15)
#5      IntroductionScreenState._onScroll (package:introduction_screen/src/introduction_screen.dart:362:9)
#6      _NotificationElement.onNotification (package:flutter/src/widgets/notification_listener.dart:130:38)
#7      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3094:18)
```

Proposal:
Wrap setState in WidgetsBinding.instance.addPostFrameCallback to avoid setState calls during build.

**Comment by ghenry** [comment]
Hi @PAException 

I presume this isn't an issue any more since you've haven't provided any more details on devices of Flutter / Os versions etc.

Closing for now. Please re-open if not and provide some more details :-)

Thanks,
Gavin.
